### ISSUE TITLE
unknow problem: navmesh is not builded

### ISSUE THREAD

**Issue by FranciscoBozzo** [Tugcga/PyRecastDetour#2]
i am trying to run this simple hand-written raw points and indexes but the navmesh does not get resolved

![image](https://user-images.githubusercontent.com/67617765/133506153-1f8f46f1-2932-4f5d-9171-f6390b08e462.png)

**Comment by Tugcga** [comment]
The reason in the size of the geometry you used for navmesh. As I understand, the system use some voxelization approaches for building navmesh geometry. By default it use voxels with size 0.3. So, your geometry contains too small voxels count. As written on the log: 7 voxel for each side of the plane. 

There are two solutions:
1. Use scaled geometry. For example, use plane with coordinates 10.0... instead of 1.0...
2. Before building navmesh set properties to use small voxel cell size
```
settings = navmesh.get_settings()  # this will return a dictionary
settings["cellSize"] = 0.03  # set the size of the voxels
navmesh.set_settings(settings)  # assign settings
```

**Comment by FranciscoBozzo** [comment]
this works like a charm now

thank you!
